export default {
  EXPAND: 'EXPAND',
  HELP_DRAWER: 'HELP_DRAWER',
  SECURITY_DRAWER: 'SECURITY_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',
  CALLER_DETAILS_DRAWER: 'CALLER_DETAILS_DRAWER',
  DRAGABBLE_FORM: 'DRAGABBLE_FORM',
};
